### ISSUE TITLE
Use named Mobx actions in Mutators

### ISSUE THREAD

**Issue by dev-tim** [microsoft/satcheljs#132]
Hello folks!

I tried to use satchel with mobx dev tools and I found out actions are recorded inside of mobx as 'unnamed actions'. This makes debugging using dev tools harder.

![image](https://user-images.githubusercontent.com/5173831/68904467-4aa64980-073e-11ea-822c-00b9db8ea5f6.png)

Suggestion I have is extending mutator API and adding option to use named actions from mobx or using `action.type` as mobx action name. 
https://mobx.js.org/refguide/action.html

WDYT about this approach?

**Comment by smikula** [comment]
I agree, this would be a good idea.  It wouldn't be that hard to use the Satchel action type as the MobX action name.  This doesn't 100% solve the problem because many mutators might respond to the same action, but in practice it's probably good enough.

We could add the optional parameter to mutators, but I'm wary of adding another field that's purely for diagnostic purposes.  (Satchel's `action.type` is already superfluous except for diagnostics.)

**Comment by dev-tim** [comment]
Reusing `action.type` should be 100% sufficient. I'll prepare a PR that uses named actions.

**Comment by dev-tim** [comment]
Added PR with kind of naive approach - but should do the thing, happy to get some feedback.

**Comment by smikula** [comment]
@dev-tim, I just merged your change.  I'll get a new release out soon, probably Monday.  Thanks for the fix!

**Comment by smikula** [comment]
@dev-tim, I just published v4.1.0.  Let me know if you run into any more problems.
