### ISSUE TITLE
Is it inaccurate to describe satchel as "based on Flux"?

### ISSUE THREAD

**Issue by brphelps** [Microsoft/satcheljs#32]
At best, SatchelJS seems to be a simplification of the Flux architecture (and could at the same time be losing significant architectural benefits).

In Flux, Stores are responsible for interpreting the effect actions have on their data (in the prototypical Flux implementation, this is the ReduceStore, in Redux, this can be with things like Reducers). In Satchel, Actions seem to have implementation that directly reaches into stores and modifies their internal state, which actually goes against the list Best Practices for Actions on Flux's page. This actually has very significant implications, as Actions being simple, serializable "instructions" (but not imperative state changes) opens up the doors to features like replayability in a much more predictable manner.

To what extent has the design of Satchel been verified with the creators of the Flux architecture as being a potential improvement (or regression) of the architecture?

**Comment by kenotron** [comment]
You can similarly argue against any implementation against their intended interpretation of design patterns in general. Think MVVM, MVC, etc.

Satchel is a synthesis of mobx and Flux patterns. We have done many prototypes with various data flow libraries and found that in general we want to stick to these principles:

1. Shared state as provided by a state tree, the store, like Redux
2. Centrally managed dispatching of actions

As far having stores that manages the state themselves, this concept is actually more similar to what mobx out of the box recommends. Think through what you just commented here: you are arguing that we would have another concept called "reducers" (which by the way is Redux - an interpretation, based on Flux architecture). SatchelJS got rid of the reducers concept because of the amount of boilerplate code you end up having to maintain.

Think Redux action messages combined with reducer from Redux = SatchelJS actions. On the other hand, there's no smart or dumb components. We then wholesale take mobx's observable pattern and update minimal amount of UI.

If you wanted to read about where this came from, read on: https://medium.com/@kenneth_chau/the-2-fundamental-laws-of-flux-and-the-functional-reactive-flux-c9368ac008d3#.axa1pclkn. Discussion of this nature probably is more appropriate over blog comments rather than a bug.

**Comment by brphelps** [comment]
The main reason this was opened as an issue is because I think it's misleading internally -- if a team wants a solution that is an implementation of the flux architecture, I don't think this really fits. 

Have you engaged the flux community at all to see if your assessment of Satchel as being a flux implementation is considered accurate by the architecture designers themselves?

> You can similarly argue against any implementation against their intended interpretation of design patterns in general. Think MVVM, MVC, etc.

I completely agree with this -- if someone implements a framework and says "This is an MVVM framework" but in reality, it is an MVC framework, I think we should revise how we talk about the framework.

**Comment by brphelps** [comment]
Also, P.S. -- Isn't "reducer" an analogue to the reduce function found in the prototypical Flux implementation? The whole concept of reducer (or a reduceStore) is there to **prevent** anything but the store from being able to modify the contents of the store. Satchel is a significant deviation from this intention, to a point where I'd argue it violates the architectural principles of Flux.
