### ISSUE TITLE
Is the documentation up to date?

### ISSUE THREAD

**Issue by joseluisgarciaott** [Microsoft/satcheljs#74]
I believe the documentation from https://microsoft.github.io/satcheljs/book/ is not updated, I can't find any references to Mutator or Orchestrators. 

I really like what you are doing here based on Mobx! So it would be great if you can upload some neat examples! Or go even further and create a todo-app :)

Thanks!

**Comment by smikula** [comment]
You're right, the documentation is a little out of sync here.  We haven't updated the book since we haven't officially released v3 yet, but the updated documentation is written and you can see it in this branch:

https://github.com/Microsoft/satcheljs/tree/gh-pages-vnext

And we do have a TodoMVC app too!  It's here:

https://github.com/Microsoft/satcheljs-todomvc/tree/vnext

Again a bit out of sync since we're still trying to lock down our v3 API, but once we do we'll update the TodoMVC app to match.

**Comment by joseluisgarciaott** [comment]
Great! I didn't saw the branches. keep up the good work!
